'use client'

import Image from 'next/image'
import { useState, useEffect, useRef } from 'react'
import { type Ground } from '@/lib/grounds'
import { cn } from '@/lib/utils'
import { motion, AnimatePresence } from 'framer-motion'
import { Cloud, Wind, Thermometer, Droplets, Trophy, Info, Lightbulb, MapPin, Gauge, Download, Loader2 } from 'lucide-react'
import type { WeatherData } from './main-app'
import { FinancialScoreCards } from '@/components/ui/financial-score-cards'
import { InteractivePitchModel } from '@/components/ui/3d-pitch-model'
import { PitchDecayVisualizer } from '@/components/ui/pitch-decay-visualizer'
import { PitchVerdictGenerator } from '@/components/ui/pitch-verdict-generator'
import { toPng } from 'html-to-image'
import { jsPDF } from 'jspdf'

/* ── Icon mapper ── */
function wttrIcon(code: string) {
  const c = parseInt(code)
  if (c === 113) return <Cloud className="w-6 h-6 text-amber-400" />
  if (c <= 116) return <Cloud className="w-6 h-6 text-zinc-400" />
  if (c <= 122) return <Cloud className="w-6 h-6 text-zinc-500" />
  if (c <= 200) return <Cloud className="w-6 h-6 text-zinc-600" />
  return <Thermometer className="w-6 h-6 text-teal-400" />
}

export function GroundsView({ ground, weather, weatherError }: { ground: Ground; weather: WeatherData | null; weatherError: boolean }) {
  const reportRef = useRef<HTMLDivElement>(null)
  const [isDownloading, setIsDownloading] = useState(false)

  const handleDownloadPDF = async () => {
    if (!reportRef.current) return
    setIsDownloading(true)
    
    try {
      // Pause to ensure all animations and the 3D WebGL buffer are fully resolved
      await new Promise(res => setTimeout(res, 500))
      
      const width = reportRef.current.offsetWidth
      const height = reportRef.current.offsetHeight
      
      const dataUrl = await toPng(reportRef.current, {
        backgroundColor: '#09090b',
        pixelRatio: 2, // Retain high density for the PDF
        cacheBust: true,
      })
      
      // Match PDF dimensions exactly to the DOM node for a flawless replica
      const pdf = new jsPDF({
        orientation: height > width ? 'portrait' : 'landscape',
        unit: 'px',
        format: [width, height]
      })
      
      pdf.addImage(dataUrl, 'PNG', 0, 0, width, height)
      pdf.save(`HitTheDeck-${ground.short}-Intelligence.pdf`)
    } catch (err) {
      console.error('Failed to generate PDF report', err)
      alert("Failed to generate PDF report. Please check the console.")
    } finally {
      setIsDownloading(false)
    }
  }

  return (
    <div className="space-y-12">
      {/* Container for the PDF capture scope */}
      <div ref={reportRef} className="space-y-12 pb-6 px-4 -mx-4 bg-zinc-950">
      {/* 1. Statistics Pulse - Global Overview */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
      >
        <FinancialScoreCards ground={ground} />
      </motion.div>

      {/* 2. Main Intelligence Panel */}
      <motion.div 
        className="bg-zinc-900/40 backdrop-blur-2xl border border-white/5 rounded-[2.5rem] overflow-hidden shadow-[0_24px_48px_-12px_rgba(0,0,0,0.5)]"
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 0.2 }}
      >
        <div className="p-8 lg:p-12">
          <GroundPanel ground={ground} weather={weather} weatherError={weatherError} />
        </div>
      </motion.div>

      {/* 3. Pitch Decay Visualizer */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 0.4 }}
      >
        <PitchDecayVisualizer ground={ground} />
      </motion.div>

      {/* 4. Pre-Match Pitch Verdict */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 0.5 }}
      >
        <PitchVerdictGenerator ground={ground} weather={weather} />
      </motion.div>

      {/* 5. Innings Behavior - Timeline View */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, delay: 0.6 }}
      >
        <div className="px-4">
          <SectionHead className="mb-8">Development Timeline</SectionHead>
          <InningsTimeline ground={ground} />
        </div>
      </motion.div>
      
      {/* PDF Watermark - Visible within the final PDF at the very bottom */}
        <div className="pt-8 flex items-center justify-center gap-2 opacity-50 pb-4">
           <span className="w-1.5 h-1.5 rounded-full bg-teal-500" />
           <span className="text-[10px] font-bold uppercase tracking-[0.3em] text-zinc-500">Generated by HitTheDeck</span>
        </div>
      </div>
      
      {/* Print PDF Action - Lives OUTSIDE the capture ref */}
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1 }}
        className="flex justify-center pt-8 border-t border-white/5"
      >
        <button
          onClick={handleDownloadPDF}
          disabled={isDownloading}
          className={cn(
            "flex items-center gap-2 px-6 py-3 rounded-full text-xs font-bold uppercase tracking-wider transition-all border",
            isDownloading 
              ? "bg-white/5 text-zinc-500 border-white/5 cursor-not-allowed"
              : "bg-teal-500/10 text-teal-400 border-teal-500/30 hover:bg-teal-500/20 hover:scale-105 shadow-[0_0_20px_rgba(20,184,166,0.15)]"
          )}
        >
          {isDownloading ? (
            <><Loader2 className="w-4 h-4 animate-spin" /> Generating PDF...</>
          ) : (
            <><Download className="w-4 h-4" /> Download Scout PDF Report</>
          )}
        </button>
      </motion.div>
    </div>
  )
}

function GroundPanel({ ground: g, weather, weatherError }: { ground: Ground; weather: WeatherData | null; weatherError: boolean }) {
  const images = g.gallery && g.gallery.length > 0 ? g.gallery : [g.tsimage]
  const [currentIdx, setCurrentIdx] = useState(0)

  useEffect(() => {
    if (images.length > 1) {
      const interval = setInterval(() => {
        setCurrentIdx((prev) => (prev + 1) % images.length)
      }, 5000)
      return () => clearInterval(interval)
    }
  }, [images.length])

  return (
    <div className="flex flex-col gap-16">
      {/* 1. Identity Section - Full Width */}
      <div className="space-y-6">
        <div className="flex items-center gap-3">
          <div className="px-3 py-1 rounded-full bg-teal-500/10 border border-teal-500/20">
             <span className="text-[10px] font-bold tracking-[0.2em] text-teal-500 uppercase">{g.city}</span>
          </div>
          <span className="text-[10px] font-bold tracking-[0.2em] text-zinc-600 uppercase">Est. {g.est}</span>
        </div>
        
        <h2 className="text-5xl md:text-7xl lg:text-8xl font-black tracking-tighter text-zinc-50 leading-[0.9]">{g.name}</h2>
        
        <p className="text-lg md:text-xl leading-relaxed text-zinc-400 font-medium max-w-3xl">
          {g.narrative}
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
        {/* Left Column: Visuals & Core Metrics */}
        <div className="lg:col-span-7 space-y-12">
          {/* Cinematic Gallery */}
          <div className="relative w-full h-[250px] md:h-[400px] rounded-[2.5rem] overflow-hidden border border-white/5 shadow-2xl">
             <AnimatePresence mode="popLayout">
               <motion.div
                 key={currentIdx}
                 initial={{ opacity: 0, scale: 1.05 }}
                 animate={{ opacity: 1, scale: 1 }}
                 exit={{ opacity: 0 }}
                 transition={{ duration: 1.2 }}
                 className="absolute inset-0 z-0"
               >
                 <Image
                   src={images[currentIdx].url}
                   alt={images[currentIdx].alt}
                   fill 
                   priority={currentIdx === 0}
                   sizes="(max-width: 900px) 100vw, 50vw"
                   className="object-cover"
                 />
               </motion.div>
             </AnimatePresence>
             <div className="absolute inset-0 bg-gradient-to-t from-zinc-950 via-transparent to-transparent z-10" />
             <div className="absolute bottom-8 right-8 z-20">
                {images.length > 1 && (
                  <div className="flex gap-2 items-center bg-black/40 px-4 py-2.5 rounded-2xl backdrop-blur-md">
                    {images.map((_, i) => (
                      <div key={i} className={cn("w-1.5 h-1.5 rounded-full transition-all duration-500", i === currentIdx ? "bg-teal-400 scale-125 shadow-[0_0_10px_rgba(45,212,191,0.5)]" : "bg-white/20")} />
                    ))}
                  </div>
                )}
             </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
             <div className="space-y-6">
                <SectionHead>Real-time Intelligence</SectionHead>
                <WeatherStrip weather={weather} error={weatherError} />
             </div>
             <div className="space-y-6">
                <SectionHead>Surface Traits</SectionHead>
                <TraitCard ground={g} />
             </div>
          </div>
        </div>

        {/* Right Column: AI Modeling & Data Bento */}
        <div className="lg:col-span-5 space-y-12">
          <div className="space-y-6">
             <SectionHead>Predictive Heatmap</SectionHead>
             <InteractivePitchModel ground={g} />
          </div>

          <div className="space-y-6">
             <SectionHead>Venue Data</SectionHead>
             <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
               {g.intel.map((item, idx) => (
                 <motion.div 
                   key={item.label}
                   initial={{ opacity: 0, y: 10 }}
                   animate={{ opacity: 1, y: 0 }}
                   transition={{ delay: 0.2 + (idx * 0.1) }}
                   className={cn(
                     "p-6 rounded-3xl border border-white/5 bg-white/[0.02] hover:bg-white/[0.04] transition-all group",
                     idx === 2 && "sm:col-span-2"
                   )}
                 >
                   <div className="flex items-start justify-between mb-4">
                     <div className="p-2 rounded-xl bg-teal-500/10 text-teal-500">
                        {idx === 0 && <Droplets size={18} />}
                        {idx === 1 && <Lightbulb size={18} />}
                        {idx === 2 && <Trophy size={18} />}
                        {idx === 3 && <Info size={18} />}
                     </div>
                   </div>
                   <h4 className="text-[10px] font-bold tracking-[0.2em] uppercase text-zinc-500 mb-2">{item.label}</h4>
                   <p className="text-[15px] font-semibold text-zinc-200 leading-snug group-hover:text-zinc-50 transition-colors">
                     {item.value}
                   </p>
                 </motion.div>
               ))}
             </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function WeatherStrip({ weather, error }: { weather: WeatherData | null; error: boolean }) {
  if (error || !weather) {
    return (
      <div className="p-6 rounded-3xl border border-white/5 bg-white/[0.02] flex items-center gap-4">
        <div className="w-10 h-10 rounded-2xl bg-zinc-800 flex items-center justify-center animate-pulse" />
        <div className="space-y-2">
          <div className="w-24 h-4 bg-zinc-800 rounded animate-pulse" />
          <div className="w-32 h-3 bg-zinc-800 rounded animate-pulse" />
        </div>
      </div>
    )
  }

  return (
    <div className="p-1 rounded-3xl border border-teal-500/20 bg-teal-500/5 relative overflow-hidden group">
      <div className="p-6 flex items-center gap-5 relative z-10">
        <div className="p-3 bg-teal-950/40 rounded-2xl border border-teal-500/20">
          {wttrIcon(weather.code)}
        </div>
        <div className="flex-1">
          <div className="text-xl font-bold text-zinc-50">{weather.temp}°C · {weather.desc}</div>
          <div className="text-xs font-bold text-zinc-500 uppercase tracking-widest mt-1">
            Feels {weather.feels}°C · Hum {weather.hum}% · Wind {weather.wind} km/h
          </div>
        </div>
        <div className={cn(
          "px-3 py-1 rounded-full text-[9px] font-bold uppercase tracking-widest border",
          weather.highDew ? "bg-red-500/10 text-red-400 border-red-500/30" : "bg-teal-500/10 text-teal-400 border-teal-500/30"
        )}>
          {weather.highDew ? "High Dew Risk" : "Low Dew Risk"}
        </div>
      </div>
    </div>
  )
}

function TraitCard({ ground: g }: { ground: Ground }) {
  return (
    <div className="space-y-6">
      <SectionHead>Pitch Profile</SectionHead>
      <div className="space-y-5">
        {(Object.keys(g.traits) as (keyof Ground["traits"])[]).map((trait, idx) => (
          <div key={trait} className="space-y-2">
            <div className="flex justify-between items-end">
              <span className="text-[11px] font-bold tracking-widest text-zinc-400 uppercase">{trait}</span>
              <span className="text-sm font-bold text-zinc-50">{g.traits[trait]}%</span>
            </div>
            <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
               <motion.div 
                 initial={{ width: 0 }}
                 animate={{ width: `${g.traits[trait]}%` }}
                 transition={{ duration: 1.2, delay: 0.6 + (idx * 0.1), ease: "circOut" }}
                 className="h-full rounded-full relative"
                 style={{ background: g.traitColors[trait] }}
               >
                 <div className="absolute inset-0 bg-white/20 blur-sm opacity-50" />
               </motion.div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

function InningsTimeline({ ground: g }: { ground: Ground }) {
  return (
    <div className="relative pt-12">
      {/* The Line */}
      <div className="absolute top-[4.5rem] left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />
      
      <div className="grid grid-cols-1 md:grid-cols-4 gap-8 relative z-10">
        {g.innings.map((inn, idx) => (
          <motion.div 
            key={inn.num}
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.8 + (idx * 0.1) }}
            className="flex flex-col items-center text-center group"
          >
            {/* The Dot */}
            <div className="mb-6 relative">
               <div className="w-10 h-10 rounded-2xl bg-zinc-950 border border-white/10 flex items-center justify-center text-[10px] font-bold text-zinc-400 group-hover:border-teal-500/50 group-hover:text-teal-400 transition-all">
                  {inn.num}
               </div>
               {idx < 3 && (
                 <div className="absolute left-[3rem] top-1/2 w-[calc(100%+2rem)] h-px bg-white/5 hidden md:block" />
               )}
            </div>
            
            <h4 className="text-sm font-bold text-zinc-50 mb-1">{inn.label}</h4>
            <p className="text-[11px] text-zinc-500 font-medium max-w-[140px] leading-relaxed group-hover:text-zinc-400 transition-colors">
              {inn.note}
            </p>
          </motion.div>
        ))}
      </div>
    </div>
  )
}

function SectionHead({ children, className }: { children: React.ReactNode; className?: string }) {
  return (
    <div className={cn('flex items-center gap-4', className)}>
      <span className="text-[11px] font-bold tracking-[0.25em] uppercase text-zinc-600 whitespace-nowrap">
        {children}
      </span>
      <div className="h-px w-12 bg-teal-500/30" />
    </div>
  )
}
